### PR TITLE
Fixing time budget issue in AmbieGenVAE

### PR DESCRIPTION
**Pull request by dgumenyuk**
In this pull request, we added a new termination for our test generator, which should fix the issue of getting exceptions for low time budgets.
With my best regards,
Dmytro

### CODE REVIEW

**Comment by matteobiagiola** [comment]
Hi Dmytro,

I'm sorry to bother you again, unfortunately there is another error. The stacktrace is below:

```
Traceback (most recent call last):
  File "competition.py", line 397, in generate
    test_generator.start()
  File "C:\Users\conceptd\workspace\cps-tool-competition\ambiegenvae\ambiegenvae_generator.py", line 125, in start
    res = self.run_optimization()
  File "C:\Users\conceptd\workspace\cps-tool-competition\ambiegenvae\ambiegenvae_generator.py", line 94, in run_optimization
    res = minimize(
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\site-packages\pymoo\optimize.py", line 67, in minimize
    res = algorithm.run()
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\site-packages\pymoo\core\algorithm.py", line 141, in run
    self.next()
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\site-packages\pymoo\core\algorithm.py", line 162, in next
    self.advance(infills=infills)
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\site-packages\pymoo\core\algorithm.py", line 223, in advance
    self._post_advance()
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\site-packages\pymoo\core\algorithm.py", line 321, in _post_advance
    obj = copy.deepcopy(self)
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\copy.py", line 205, in _deepcopy_list
    append(deepcopy(a, memo))
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\copy.py", line 210, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\copy.py", line 210, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\copy.py", line 210, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\copy.py", line 210, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\copy.py", line 296, in _reconstruct
    value = deepcopy(value, memo)
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\conceptd\anaconda3\envs\sbst-ambiegen\lib\copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle '_thread.RLock' object
```

It happens consistently in every run, and after about 5 minutes of starting the tool. Maybe it is related to the latest changes.

Best,

Matteo

**Comment by dgumenyuk** [comment]
Dear Matteo, thank you for letting us know. I would like to assure you that on our end this error has never appeared. It reminds me of the error you encountered with RIGAA last year... It was also related to "copy" library, but this time this is the "copy" operation happening inside pymoo and we have less control over it. Could you let me know, what version of python are you using? We are using Python 3.9.18 . I will try to replicate this error with your version of python.

**Comment by matteobiagiola** [comment]
Thanks for the quick reply. I tried to run the tool with python 3.9.18 (was using python 3.8). 

It seems that the issue did not manifest in a 1 hour run with the beamng agent; I'm now running the dave2 agent for the same budget. 

I'll let you know if the problem persists.

**Comment by dgumenyuk** [comment]
Thank you for your reply Matteo! And thank you for trying out another python version, I hope it will solve the issue. Sure, let us know if there are any problems with Dave2 agent!

**Comment by matteobiagiola** [comment]
I did another 1h run with the beamng agent, and the problem did not occur.

However, with the dave2 agent, it occurs consistently after 17--19 tests (at least on my machine). Can you reproduce this behavior on your hardware?

Thanks!

**Comment by dgumenyuk** [comment]
Matteo hi! Are you using the run.py script to launch the tool? When I am using the script "run.py" I get the following error:   File "C:\Users\gumen\anaconda3\Lib\site-packages\shapely\geos.py", line 54, in load_dll
    raise OSError(
OSError: Could not find lib geos_c.dll or load any of its variants [].
 I want to use the same script as you to have better chances of replication.

**Comment by matteobiagiola** [comment]
Yes, I'm using the run script, but probably you need to change the `python_exe` variable to point to the python executable of your virtual environment (or conda environment) where you installed the dependencies, if you are using any. 

I guess you already changed the `beamng_user` and `beamng_home` variables; other than that, it should work.

**Comment by dgumenyuk** [comment]
Dear Matteo, indeed, I could replicate the issue, when running with the Dave2 agent. However, I have never had this issue with BeamNg agent, which I tested for multiple hours. I got the following issue:
023-12-13 15:51:09,807 CRITICAL An error occurred during test generation
Traceback (most recent call last):
  File "C:\DIMA\PHD_YEAR3\SBFT2024_TOOL_COMPETITION\cps-tool-competition\competition.py", line 397, in generate   
    test_generator.start()
  File "C:\DIMA\PHD_YEAR3\SBFT2024_TOOL_COMPETITION\cps-tool-competition\ambiegenvae\ambiegenvae_generator.py", line 125, in start
    res = self.run_optimization()
  File "C:\DIMA\PHD_YEAR3\SBFT2024_TOOL_COMPETITION\cps-tool-competition\ambiegenvae\ambiegenvae_generator.py", line 94, in run_optimization
    res = minimize(
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\site-packages\pymoo\optimize.py", line 67, in minimize  
    res = algorithm.run()
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\site-packages\pymoo\core\algorithm.py", line 141, in run
    self.next()
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\site-packages\pymoo\core\algorithm.py", line 162, in next
    self.advance(infills=infills)
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\site-packages\pymoo\core\algorithm.py", line 223, in advance
    self._post_advance()
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\site-packages\pymoo\core\algorithm.py", line 321, in _post_advance
    obj = copy.deepcopy(self)
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\copy.py", line 205, in _deepcopy_list
    append(deepcopy(a, memo))
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\copy.py", line 210, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\copy.py", line 210, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\copy.py", line 210, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\copy.py", line 210, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\copy.py", line 296, in _reconstruct
    value = deepcopy(value, memo)
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\gumen\anaconda3\envs\cps_competition\lib\copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle '_thread.RLock' object


I will try to fix it. From what I see, this exception happens only for certain tests and then the search is continued.

**Comment by dgumenyuk** [comment]
If I do not fix it by around tomorrow would it be possible for you to still evaluate the generator even if the exceptions occur, i.e. some tests will be in "Error". This is disadvantageous for my tool, but at least the evaluation can be done...

**Comment by dgumenyuk** [comment]
Dear @matteobiagiola I'm sorry for the trouble. In line 101 of ambiegenvae_generator.py . `save_history` argument should be set to `False` as this: `res = minimize(
            self.problem,
            self.method,
            termination= BeamNGTermination(),
            seed=self.seed,
            verbose=False,
            eliminate_duplicates=True,
            save_history=False
        )`
This solves the issue. On my end, I could successfully execute several 1h runs for Dave 2 agent.

**Comment by matteobiagiola** [comment]
Hi Dmytro,

I confirm that the proposed fix `save_history=False`, works. I will push the change.

Thanks!

**Pull request merged**
